sudo: required
language: node_js
node_js:
  - 11
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh |  sh
  - docker login -u "$ DOCKER_USERNAME" --password-stdin
  - docker login -u "$ HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build
  # build docker images
  - docker build -t green03 / next-blog
  - docker tag green03 / next-blog registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    - docker push unqpdes / todo-list-front;
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    - heroku container: web release --app $ HEROKU_APP_NAME
